FROM python:3.9

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /usr/src/app

COPY store_data.py .

COPY requirements.txt .
RUN pip install -r requirements.txt

EXPOSE 8087/tcp
CMD [ "python", "./store_data.py" ]