FROM python:3.9

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /usr/src/app

COPY llm.py .

COPY requirements.txt .
RUN pip install -r requirements.txt

EXPOSE 8088/tcp
CMD [ "python", "./llm.py" ]